spring.application.name=Employee_Management_System

spring.datasource.url=jdbc:mysql://localhost:3306/{DB_NAME}
spring.datasource.username={USER_NAME}
spring.datasource.password={PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
